<?php
/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */
//Route::get('/', 'ProjectController@index');
ini_set('default_charset', 'utf-8');
ini_set('memory_limit', '2000M');
set_time_limit(360);
Route::get('timezone', function () {
    echo(date_default_timezone_get());
});
Route::get('bg-l2spo', 'UploadController@moveLocal2Spo');
Route::get('/', function () {
    $data['env'] = Config::get('app.cEnv');
    return View::make('users.login')->with('data', $data);
});
Route::get('bg', function () {
    echo('123<br>');
    $oc = new  Office365Controller();
    $y = $oc->testBG('XXX');
    echo($y.'<br><br>');
    exit;
});
Route::get('testXML', 'XMLController@testXML');
Route::get('uploadAvisCLI', 'UploadAvisController@uploadAvisCLI');
Route::get('login', function () {
    $data['env'] = Config::get('app.cEnv');
    return View::make('users.login')->with('data', $data);
});
Route::controller('users', 'BISUserController');
Route::get('testpdf/{id?}', 'PDFController@pdftest');
Route::get('readInquiry', 'InquiryController@readInquiry');
Route::get('phpinfo', 'ProjectsController@get_phpinfo');
Route::get('testMail', 'TermineController@testMail');
Route::group(array('before' => 'auth'), function () {
    Route::get('cmp', function () {
        $data = array();
        $xml  = new XMLController;
        $Sals = $xml->getSALs();
        View::share('SALs', $Sals);
        $data['content'] = $xml->compareXML(6105, "LATEST", "HALLO");
        return View::make('main', $data);
    });
    Route::get('users', function () {
        $users = User::all();
        return View::make('users')->with('users', $users);
    });
    // Test Route
    //Route::get('mx/{id?}', 'ProjectsController@getMitarbeiterProjekt');
    Route::post('setsearch', 'ProjectsController@setSearch');
    Route::get('translateX', 'ProjectsController@translateDeepl');
    Route::get('userslist', 'BISUserController@getShowUsersList');
    Route::get('home', 'TermineController@getTermineDashboard');
    Route::get('homeX', 'TermineController@showlist');
    Route::get('test/{id?}', 'TermineController@getTest');
    Route::get('diffpp/{id?}', 'DiffController@getDiff');
    Route::get('diffRevision/{id?}', 'DiffController@getDiffRevision');
    Route::get('dbmigrate', 'DbmigrateController@index');
    Route::get('project', 'ProjectController@index');
    Route::get('showIAN/{ian?}/{ausm?}', 'ProjectsController@showIAN');
    Route::get('showAfterUpload/{id?}/{mainTab?}/{subTab?}/{subTabIndex?}/{subsubTabIndex?}/{compactView?}', 'ProjectsController@showAfterUpload');
    Route::get('showInquiry/{id?}/{avisid?}/{diff?}/{IsInquiry?}', 'ProjectsController@show');
    Route::get('copyPP/{id?}', 'ProjectsController@copyPP');
    Route::post('showp/{id?}', 'ProjectsController@show');
    Route::post('deletep/{id?}', 'ProjectsController@deletePP');
    Route::post('postdeletep', 'ProjectsController@postdeletep');
    Route::get('search', 'ProjectsController@showlist');
    Route::get('showlist/{sort?}', 'ProjectsController@showlist');
    Route::post('update/{id?}', 'ProjectsController@update');
    Route::post('updateRemark', 'ProjectsController@updateRemark');
    Route::post('newRemark', 'ProjectsController@newRemark');
    Route::post('updateq', 'ProjectsController@updateQualitaet');
    Route::post('update8W', 'ProjectsController@update8W');
    Route::post('updatepo', 'ProjectsController@updatePO');
    Route::post('updatem', 'ProjectsController@updateMenge');
    Route::post('updatelc', 'ProjectsController@updateLC');
    Route::post('createArtikelERP', 'ProjectsController@createArtikelERP');
    Route::post('formsubmit/{RefNumber?}', 'ProjectController@save');
    Route::get('check/{id}', 'UploadController@check_Sortierung');
    Route::get('toXLS/{id?}', 'ExcelController@writeExcel');  
    Route::get('readThemenplanung/{id?}', 'ExcelController@readThemenplanung');
    Route::get('showImportThemenplanung', 'ExcelController@showImportThemenplanung');
    Route::post('importThemenplanung', 'ExcelController@importThemenplanung');
    Route::get('fromXLS/{file}/{heimtex}/{force}', 'ExcelController@fromXLS');
    Route::get('getExcelPics/{id}', 'ExcelController@getExcelPics');
    Route::post('forceXLS', 'UploadController@forceXLS');
    Route::get('imgXLS', 'ExcelController@getExcelimage');
    Route::get('uploadForm/{IsInquiry}', 'UploadController@getUploadForm');
    Route::get('uploadAvisForm', 'UploadAvisController@getUploadAvisForm');
    Route::post('uploadAvis', 'UploadAvisController@uploadAvis');
    Route::post('upload', 'UploadController@upload');
    Route::get('importXLS', 'ExcelController@getUploadForm');
    Route::get('terminePowerBI/{pjn}/{sortart?}/{board?}/{start?}', 'TermineController@showlistPowerBI');
    Route::get('termine/{sort?}/{sortart?}/{board?}/{start?}', 'TermineController@showlist');
    Route::get('changeManSoll', 'TermineController@changeManSoll');
    Route::post('termine/{sort?}/{sortart?}/{board?}/{start?}', 'TermineController@showlist');
    Route::get('termineReset', 'TermineController@showlist_ohneSession');
    Route::get('terminEdit/{id}', 'TermineController@editTermin');
    Route::get('terminliste/{sort?}', 'TermineController@postTerminlisteFilter');
    Route::get('terminlisteM/{sort?}', 'TermineController@postTerminlisteFilterM');
    Route::get('terminlisteI/{sort?}', 'TermineController@postTerminlisteFilterI');
    Route::post('terminlisteFilter', 'TermineController@postTerminlisteFilter');
    Route::get('colAusblenden/{id?}', 'TermineController@getAusblenden');
    Route::get('colEinblenden/{id?}', 'TermineController@getEinblenden');
    Route::get('colEinblendenAlle', 'TermineController@getEinblendenAlle');
    Route::get('colStatusSave', 'TermineController@saveColStatus');
    Route::get('markRow/{id?}', 'TermineController@getMarkRow');
    Route::post('setMA_PM_TC', 'TermineController@setMA_PM_TC');
    Route::post('setVTR', 'TermineController@setVTR');
    Route::get('terminDashboard', 'TermineController@getTermineDashboard');
    Route::post('testAjax', 'TermineController@testAjax');
    Route::get('addTS', 'TermineController@ergaenzeNeueTerminspalten');
    Route::get('repairTermine', 'TermineController@ergaenzeNeueTerminspalten');
    Route::post('drop', 'ProjectsController@updateThema');
    Route::get('terminedetails/{id?}', 'TermineController@show');
    Route::post('termineupdate/{id?}/{form?}', 'TermineController@update');
    Route::post('termineupdatejson', 'TermineController@updatejson');
    Route::any('termineupdatejsonM', 'TermineController@updatejsonMusterung');
    Route::post('setChangeErledigt', 'TermineController@setChangeErledigtM');
    Route::post('newTheme', 'TermineController@newTheme');
    Route::post('termineModifyState', 'TermineController@modifyState');
    Route::post('termineChangeStateAnswer', 'TermineController@setChangeAnswerM');
    Route::post('termineChangeState', 'TermineController@updatejsonChangeState');
    Route::post('newProjekt/{id?}', 'TermineController@newProjekt');
    Route::get('getnewProjekt/{id?}', 'TermineController@newProjekt');
    Route::post('uploadFiles', 'UploadController@uploadFilesSharepoint');
    Route::post('uploadFilesTermine', 'UploadController@uploadFilesTermine');
    Route::post('deleteFiles/{id?}', 'UploadController@deleteFiles');
    Route::post('setProjectPic', 'UploadController@setProjectPic');
    Route::post('updateRemarkFiles', 'UploadController@updateRemarkFiles');
    Route::post('exportPP/{id?}', 'UploadController@exportPP');
    Route::post('upload2Sharepoint', 'UploadController@upload2Sharepoint');
    Route::post('exportPPFinal/{id?}', 'UploadController@exportPP_Final');
    Route::post('downloadFiles/{id?}', 'UploadController@putDownload');
    Route::post('writeABFinal/{id?}', 'UploadController@exportAB_Final');
    Route::post('writeAnlageFinal/{id?}', 'UploadController@exportAnlage_Final');
    Route::post('writeAB/{id?}', 'UploadController@exportAB');
    Route::post('writeAnlage/{id?}', 'UploadController@exportAnlage');
    Route::controller('mitarbeiter', 'MitarbeiterController');
    Route::get('bulkPW', 'MitarbeiterController@bulkPwChange');
    Route::get('frmChangePassword', 'MitarbeiterController@frmChangePassword');
    Route::post('changePassword', 'MitarbeiterController@postChangePassword');
    Route::post('deleteMitarbeiter', 'MitarbeiterController@deleteMitarbeiter');
    Route::get('finance', 'FinanceController@Index');
    Route::post('saveDTK', 'FinanceController@SaveDTK');
    Route::post('showDTK', 'FinanceController@ShowDTK');
    Route::post('newDTKAssign', 'FinanceController@NewDTKAssign');
    Route::post('saveDTKAssign', 'FinanceController@SaveDTKAssign');
    Route::post('assignDTKAssign', 'FinanceController@AssignDTKAssign');
    Route::get('showUngedeckt', 'FinanceController@ShowUngedeckt');
    Route::post('showUngedeckt', 'FinanceController@ShowUngedeckt');
    Route::any('showLiq', 'FinanceController@ShowLiquiditaet');
    Route::post('saveLiq', 'FinanceController@saveLiquiditaet');
    Route::any('handleFiles', 'ProjectsController@handleFiles');
    Route::any('show8W', 'ProjectsController@show8W');
    Route::any('showLC', 'FinanceController@showLCOv');
    Route::any('showOrderAll1', 'FinanceController@showOrderOv'); 
    Route::any('showOrderAll', 'ProjectsController@showOrderAll');
    Route::any('showLiqAll', 'FinanceController@showLiqAll');
    //Route::get('DevisenTerminKauf', 'FinanceController@DevisenTerminKauf');
    Route::controller('adressen', 'AdressenController');
    Route::post('sucheAdresse', 'AdressenController@suche');
    //Validator
    Route::post('updateThema', 'ProjectsController@updateThema');
    Route::post('updatepurchase/{id?}', 'ProjectsController@updatepurchase');
    Route::post('updateab/{id?}', 'ProjectsController@updateAB');
    Route::post('updatesort', 'ProjectsController@updateSort');
    Route::post('updatestyle', 'ProjectsController@updateStyle');
    Route::post('updateLieferavis', 'ProjectsController@updateAvis');
    Route::get('Lieferavis2XML/{id}', 'ProjectsController@Avis2XML');
    //Route::post('outPDF/{id?}', 'PDFController@outputPDF');
    Route::post('outPDFP/{id?}/{bw?}', 'PDFController@outputPDFP');
    Route::post('outPDFPFinal/{id?}/{bw?}', 'PDFController@outputPDFP_Final');
    Route::post('outPDFLC/{id?}', 'PDFController@outputLC');
    Route::post('outPDFLCFinal/{id?}/{final?}', 'PDFController@outputLC');
    Route::post('outPDF8W/{id?}', 'PDFController@output8W');
    Route::controller('json', 'JsonController');
    Route::controller('EAN', 'EANController');
    Route::controller('textbausteine', 'TextbausteineController');
    Route::controller('warengruppen', 'WarengruppenController');
    Route::controller('stammdaten/{art}', 'StammdatenController');
    Route::post('saveStammaus', 'StammdatenController@saveStammaus');
    Route::post('updateStatus', 'TermineController@updateStatus');
    Route::post('filterTermine', 'TermineController@filterTermine');
    Route::post('setRPinaktiv', 'ProjectsController@setRPinaktiv');
    Route::get('updateDefaultMA', 'TermineController@setDefaultMA_Termine');
    Route::get('deleteDoppelteTermine', 'TermineController@loescheDoppelteTermineAusDatenbankAdmin');
    Route::get('ppOverviewStart', 'ProjectsController@ppOverviewStart');
    Route::post('ppOverviewStart', 'ProjectsController@ppOverviewStart');
    Route::get('formDeleteIAN', 'ProjectsController@showDeleteIAN');
    Route::post('deleteIAN', 'ProjectsController@deleteIAN');
    Route::get('originalExcel/{id}', function ($id) {
        if (PPProduktpass::find($id)->exists()) {
            $pp   = PPProduktpass::find($id);
            //echo($pp->PPProduktpass_AktExcel);
            $file = storage_path() . "/data/" . $pp->PPProduktpass_AktExcel;
            //echo($file);exit;
            return Response::download($file);
        }
        //$filepath = storage_path() . '/data/' . PPProduktpass::find($id)->PPProuktpass_AktExcel;
        //return Response::download($filepath);
    });
    Route::get('ExcelForm', 'NewExcelController@ExcelForm');
    Route::post('ExcelAuswertung', 'NewExcelController@ExcelAuswertung');
    Route::post('ExcelEKVKRohertrag', 'NewExcelController@ExcelAuswertungEKVKRohertrag');
    Route::get('ExcelInquiryForm', 'ExcelInquiryController@ExcelForm');
    Route::post('ExcelInquiry', 'ExcelInquiryController@ExcelInquiry');
    Route::get('getExcelInquiry/{ian}/{art?}', 'ExcelInquiryController@getExcelInquiry');
    Route::get('getExcelQM/{ian}/{art?}', 'ExcelInquiryController@getExcelInquiry');
    Route::get('newMusterung', 'XMLController@newXMLMusterung');
    Route::get('iFrameUpload', 'UploadController@iFrameUpload');
    Route::any('showInquiryAll', 'InquiryController@listInquiry');
    Route::any('getInquiryDiff/{id}', 'InquiryController@getDiff');
    Route::any('importXMLZip', 'XMLController@importXMLZip');
    Route::any('massenImportXML', 'XMLController@massenImportXML');
    Route::any('importXML', 'XMLController@importXML');
    Route::any('importXMLInq', 'XMLController@importXMLInq');
    Route::any('compareXML', 'XMLController@compareXML');
    Route::get('compareXMLExt/{ppid}/{fileId}', 'XMLController@compareXMLExt');
    Route::get('compareXMLFiles/{fileId1}/{FileId2}', 'XMLController@compareXMLFiles');
    Route::any('ajax_getTermin', 'TermineController@ajax_getTermin');
    Route::get('getTerminFromId/{ppid}/{tid}/{board?}/{select?}/{onlyOpen?}', 'TermineController@getTerminFromId');
    Route::get('DEVgetTerminFromId/{ppid}/{tid}/{board?}/{select?}/{onlyOpen?}', 'TermineController@DEVgetTerminFromId');
    Route::get('getTerminFromIAN/{ian_ausm}/{tid?}/{board?}/{select?}/{onlyOpen?}', 'TermineController@getTerminFromIAN_AUSM');
    Route::get('testConfig', 'TermineController@testConfig');
    Route::post('saveFilter', 'TermineController@saveFilter');
    Route::post('getFilter', 'TermineController@getFilter');
    Route::post('deletePPChanges', 'TermineController@deletePPChanges');
    Route::post('deletePPChangesReverse', 'TermineController@deletePPChangesReverse');
    Route::post('saveTBProject', 'ProjectsController@saveTBProject');
    Route::post('newProdCalc', 'ProjectsController@newProdCalc');
    Route::post('updateCalc', 'ProjectsController@updateCalc');
    Route::post('deleteCalc', 'ProjectsController@deleteCalc');
    Route::post('selectCalcSupplier', 'ProjectsController@selectCalcSupplier');
    Route::get('calcFracht/{ppid}/{load}/{abgangshafen}', 'ProjectsController@calcFracht');
    Route::get('calcContainer/{menge}/{load}', 'ProjectsController@calcContainer');
    Route::get('hafen/{id}', 'ProjectsController@berechneHafenMengen');
    Route::post('ServiceAnfrage', 'ProjectsController@postServiceAnfrage');
    Route::post('saveTranslation', 'ProjectsController@saveTranslation');
    Route::get('downloadRFQ/{ppid}/{type}', 'ExcelController@writeRFQ');
    Route::get('downloadRFQn/{ppid}/{type}', 'ExcelController@writeRFQ202403');
    Route::get('deleteIANSave',  'ProjectsController@deleteIANSave');
    Route::get('uploadMultiZipForm', 'XMLController@uploadMultiZipForm');
    Route::get('uploadZipProgressForm', 'XMLController@uploadZipProgressForm');
    Route::post('uploadMassenImport', 'XMLController@uploadMassenImport');
    Route::post('updateFilesCompact', 'UploadController@updateFilesCompact');
    Route::get('upl2spo', function () {
        $data['all'] = tPPProduktpass::where('PPProduktpass_IAN','not like', '%rev%')->count();
        $data['openTransfers'] = tPPProduktpass::where('PPProduktpass_IAN','not like', '%rev%')->whereNull('PPProduktpass_Transferd2Sharepoint')->count();
        $data['transferd'] = tPPProduktpass::where('PPProduktpass_IAN','not like', '%rev%')->whereNotNull('PPProduktpass_Transferd2Sharepoint')->count();
        $data['ok'] = tPPProduktpass::where('PPProduktpass_IAN','not like', '%rev%')->where('PPProduktpass_Transferd2Sharepoint',1)->count();
        $data['error'] = tPPProduktpass::where('PPProduktpass_IAN','not like', '%rev%')->where('PPProduktpass_Transferd2Sharepoint',0)->count();
        return View::make('onePager.upload2Sharepoint')->with('data', $data);
    });
    Route::post('post_upl2spo', 'ProjectsController@upload2SharepointBulkP');
    Route::get('dbIANdirect/{ian}', 'TermineController@dbIANdirect');
    Route::get('setFS', 'ProjectsController@setFileSizes');
    Route::get('l2spo', 'UploadController@moveLocal2Spo');
    Route::get('l2spo_start', function(){
        echo("<div style='padding:20px;font-family:Tahoma;'>");
        echo("<span style='font-size:1.2em'>Hintergrund Übertragung auf den Sharepoint-Server.<br>Dateien, die auf den lokalen Server hochgeladen wurden, werden in das zugehörige Sharepoint Verzeichnis hochgeladen. </span><br>");
        echo("<a href='/l2spo' style='text-decoration:none;'><div style='width: 100px;
    height: 36px;
    background-color: dodgerblue;
    color: white;
    margin: 30px;
    border: 1px solid gray;
    padding: 10px;
    font-size: 1.75em;
    font-weight: bold;
    border: 2px solid darkblue;
    text-align: center;
}'>Start</div></a> ");
        echo("</div>");
    } );
    Route::get('tspo', 'Office365Controller@testSharepoint1');
    Route::post('setLang', 'MitarbeiterController@setLanguage');
    Route::post('existFilesSharepoint','UploadController@existFilesSharepoint');
    Route::get('spoFileInfo', 'Office365Controller@SPOFileInfo');
    Route::get('renameSPO', 'Office365Controller@renameSPO');
    Route::get('changeFileInfo','Office365Controller@changeFileInfo');
    Route::any('showFilesAll', 'ProjectsController@showFilesAll');
    Route::post('updateMeeting', 'MeetingController@update');
    Route::get('getFormUploadPruefplaene','UploadController@getFormUploadPruefplaene');
    //Route::post('uploadMassenPruefplaene','UploadController@uploadMassenPruefplaene');
    Route::post('uploadMassenPruefplaene','UploadController@uploadMassenPruefplaeneBatch');
    Route::get('/suc', function () {
        $res[] = array('Filename' => 'Das Ist eine Dateiname.pdf', 'Link' => 'https://google.de', 'Status' => 'OK', 'Color' => 'dodgerblue');
        return View::make('UploadForms.successUploadPruefplaene')->with('result', $res);
    });
    Route::get('xFiles', 'ProjectsController@xFiles');
    Route::get('aGetPP/{ian}/{charge}/{lang}', 'IANController@aGetPP');
    Route::get('aGetPPId/{id}/{lang}', 'IANController@aGetPPId');
    Route::get('aGetPPIdLidl/{id}/{lang}', 'IANController@aGetPPIdLidl');
    Route::post('content', 'IANController@content');
    Route::post('storePP', 'IANController@storePP');
    Route::post('uploadFilesNew', 'UploadController@uploadFilesNew');
    Route::post('updateProjectNotes', 'IANController@updateProjectNotes');
    Route::post('newProjectNotes', 'IANController@newProjectNotes');
    Route::post('updateMeetingAjax', 'MeetingController@updateMeetingAjax');
    Route::post('updatePPAjax', 'IANController@updatePPAjax');
    Route::post('updateRemarkFilesAjax', 'UploadController@updateRemarkFilesAjax');
    Route::post('updateProjektPicAjax', 'UploadController@updateProjektPicAjax');
    Route::get('ergaenzeNeueTerminspaltenTest', 'TermineController@ergaenzeNeueTerminspaltenTest');
    //Alt Input
    Route::post('InputManuellInit', 'ProjectsController@InputManuellInit');
    Route::post('updateInputManuell', 'ProjectsController@updateInputManuell');
    Route::post('writeInput', 'ExcelController@writeExcel_post');
    // Neu Input
    Route::post('InputManuellInitNeu', 'ProjectsController@InputManuellInitNeu');
    Route::post('updateInputManuellNeu', 'ProjectsController@updateInputManuellNeu');
    Route::post('writeInputNeu', 'ExcelController@writeExcel_postNeu');
    Route::get('showNeu/{id}/{lang?}', 'ProjectsController@showNeu');
    Route::post('deleteFileNeu/{id?}', 'UploadController@deleteFileNeu');
    Route::get('diffXML/{ppid}/{fid}/{email?}', 'XMLController@diffXML');
    Route::get('show/{id}/{deepLink?}', 'ProjectsController@showNeu');
    Route::get('showAlt/{id}', 'ProjectsController@showAlt');
    Route::post('setKeyMilestones','MasterplanController@setKeyMilestones');
    Route::get('getMpForm/{id}','MasterplanController@getMpForm');
    Route::post('refreshFiles', 'UploadController@refreshFileTab');
    Route::get('mailCompare/{id}/{fid}/{mailto?}','IANController@mailCompare');
    Route::post('setLanguage','IANController@setLanguage');
    Route::get('prj/{id}','XMLController@getProject');
    Route::post('updateZollAjax','IANController@updateZoll');
    Route::post('getZollHistory','IANController@getZollHistory');
    Route::get('tl/{text}','ProjectsController@translateDeeplPHP');
    Route::get('testMFA', 'Office365Controller@testMFA');
    Route::get('testSPOAppOnly', 'Office365Controller@testSPOAppOnly');
    Route::get('spo5', 'Office365Controller@test5');
    Route::get('spoOK1', 'Office365Controller@logintest');
    Route::get('spoCertOK', 'SPOLoginController@test9');
    Route::get('correctState', 'TermineController@correctState');
    Route::get('Zoll', 'StammdatenController@getFormZoll');
    Route::put('updateZoll/{id}', 'StammdatenController@updateZoll');
    Route::post('createZoll', 'StammdatenController@createZoll');
    Route::post('deleteZoll/{id}', 'StammdatenController@deleteZoll');
    Route::get('massTranslate', 'TermineController@massTranslateMilesones');
    Route::post('translateLive', 'IANController@translateLive');
    Route::post('saveRemarkVersion', 'IANController@saveRemarkVersion');
    Route::post('saveIsFinal', 'IANController@saveIsFinal');
    Route::post('moveFileFrom',  'Office365Controller@moveFilesSPO' );
    Route::get('so/{filter?}', 'ShipmentOverviewController@showSO');
    Route::get('ship/{filter?}', 'ShipmentOverviewController@showShip');
    Route::post('cellupdate','ShipmentOverviewController@cellUpdate'); 
    Route::get('fileCHN', 'Office365Controller@fileExistCheck' );
    Route::post('projektbildCheck', 'Office365Controller@projektbildCheck' );    
    Route::post('projektbildRepair', 'Office365Controller@projektbildRepair');
    Route::get('dlSPO', 'Office365Controller@dlSPO' );
    Route::get('frmSystem', 'SystemController@getFormSystem' );
    Route::get('testMove', 'Office365Controller@testMove' );
    Route::post('saveLot','ShipmentOverviewController@saveLot'); 
    Route::post('deleteLot','ShipmentOverviewController@deleteLot'); 
    });
